name '2016_security_guide'
maintainer 'Inversoft'
maintainer_email 'brian@inversoft.com'
license 'all_rights'
description 'Installs/Configures 2016_security_guide'
long_description 'Installs/Configures 2016_security_guide'
version '0.1.0'
